include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
    unnecessary_new: true
    prefer_const_constructors: true
    avoid_redundant_argument_values: true
